[ -z "$PS1" ] && return
export ARSENALDIR="$HOME/Arsenal"

. $ARSENALDIR/sys/base.zsh
. $ARSENALDIR/sys/function.zsh

# fzf
. $ARSENALDIR/fzf/init.zsh

# node
. $ARSENALDIR/node/init.zsh

# zsh-autosuggestions
. $ARSENALDIR/zsh-autosuggestions/source/zsh-autosuggestions.zsh
# ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=253'
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=240'
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=1000

# zsh-syntax-highlighting.zsh
. $ARSENALDIR/zsh-syntax-highlighting/source/zsh-syntax-highlighting.zsh

# conda
. $ARSENALDIR/conda/miniconda/etc/profile.d/conda.sh

# init PATH & platform profile
if [[ $PATH != "*$ARSENALDIR*" ]]; then
    export PATH="$ARSENALDIR/bin:$ARSENALDIR/bin/self:$ARSENALDIR/conda/miniconda/bin:$ARSENALDIR/bin/node:$HOME/go/bin:$PATH"
    export PYTHONPATH="."
fi

# zoxide
. $ARSENALDIR/zoxide/init.zsh

# zsh-completions
fpath=($ARSENALDIR/zsh-autosuggestions/source/src $fpath)

# Auto source ~/.platformrc
[[ -f "$HOME/.platformrc" ]] && . "$HOME/.platformrc"


chpwd() {
    if [[ -f .conda-version ]]; then
        local env=`cat .conda-version`
        [[ $CONDA_DEFAULT_ENV != $env ]] && conda activate $env
    else
        [[ -n $CONDA_DEFAULT_ENV ]] && [[ $CONDA_DEFAULT_ENV != "base" ]] &&\
            conda deactivate
    fi

    if [[ -e ".git" ]]; then
        __git_branch="`git rev-parse --abbrev-ref HEAD 2>/dev/null`"
        [[ -n $__git_branch ]] && __git_branch=" ${__git_branch}"

        zdd
    else
        __git_branch=""
    fi
}


# Auto open a default session using tmux in Linux environment
if [[ $(OSTYPE) != "macos" ]] && [[ $(OSTYPE) != "win" ]]; then
    # Set tab title to hostname of current
    echo -ne "\033]0;`hostname`\007"

    # attach or new tmux session
    local default_tmux_session="0"
	command -v tmux &> /dev/null && [ -z "$TMUX" ] &&\
        (tmux attach -t $default_tmux_session || tmux new-session -s $default_tmux_session)
fi
